server :
  forward-headers-strategy: framework

spring:
  profiles:
    active: default,local

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 103MB

  rabbitmq:
    addresses: rabbitmq
    port: 5672

  cloud:
    stream:
      function:
        definition: consumeStudyUpdate
      bindings:
        publishExploreUpdate-out-0:
          destination: explore.update
      source: publishExploreUpdate
