server :
  port : 5029

spring:
  rabbitmq:
    addresses: localhost

powsybl:
  services:
    case-server:
      base-uri: http://localhost:5000
      
gridsuite:
  services:
    -
      name: study-server
      base-uri: http://localhost:5001
    -  
      name: directory-server
      base-uri: http://localhost:5026
    -
      name: actions-server
      base-uri: http://localhost:5022
    -
      name: network-modification-server
      base-uri: http://172.17.0.1:5007
    -
      name: filter-server
      base-uri: http://localhost:5027
    -
      name: voltage-init-server
      base-uri: http://localhost:5038
    -
      name: security-analysis-server
      base-uri: http://localhost:5023
    -
      name: loadflow-server
      base-uri: http://localhost:5008