/**
 * Copyright (c) 2021, RTE (http://www.rte-france.com)
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package org.gridsuite.explore.server;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import org.springframework.boot.autoconfigure.jackson.Jackson2ObjectMapperBuilderCustomizer;
import org.springframework.boot.jackson.JsonComponentModule;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * @author Etienne Homer <etienne.homer at rte-france.com>
 */
@Configuration
public class RestTemplateConfig {
    /**
     * we alter the {@link ObjectMapper} generated by Spring using SpringBoot system
     * @return json customizer
     * @see org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration JacksonAutoConfiguration
     * @see org.springframework.boot.autoconfigure.http.HttpMessageConvertersAutoConfiguration HttpMessageConvertersAutoConfiguration
     * @see org.springframework.boot.autoconfigure.web.client.RestTemplateAutoConfiguration RestTemplateAutoConfiguration
     */
    @Bean
    public Jackson2ObjectMapperBuilderCustomizer jsonCustomizer() {
        //also from .config: spring.jackson.serialization.write-dates-as-timestamps=false
        return builder -> builder.featuresToDisable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
                //.findModulesViaServiceLoader(true)
                .modulesToInstall(new JsonComponentModule());
    }
}
